language: php

php:
  - 5.3
  - 5.4

before_install:
  - composer install
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./keystone/keystone ./laravel/bundles/keystone
  - echo "<?php return array('keystone' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test keystone"

notifications:
  email: false