language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ~/builds/keystone/keystone ~/builds/laravel/bundles/keystone
  - cd ~/builds/laravel/bundles/keystone
  - composer install
  - echo "<?php return array('keystone' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ~/builds/laravel

script: "php artisan test keystone"

notifications:
  email: false