language: php

php:
  - 5.3
  - 5.4

before_install:
  - echo "short_open_tag=On" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ~/builds/keystone/keystone ~/builds/laravel/bundles/keystone
  - cd ~/builds/laravel/bundles/keystone
  - composer install --no-interaction
  - echo "<?php return array('keystone' => array('auto' => true));" > ~/builds/laravel/application/bundles.php
  - cd ~/builds/laravel/bundles/keystone

script: "php phpunit.phar"

notifications:
  email: false
